# Generated by Django 4.2.4 on 2025-07-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OwnerInterface", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkinglot",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="parking_images/"),
        ),
    ]
