# Generated by Django 5.2.4 on 2025-07-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OffStreetCP",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("car_park_id", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "emergency_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("position_lat", models.FloatField(blank=True, null=True)),
                ("position_lon", models.FloatField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("car_park_id", "city")},
            },
        ),
        migrations.CreateModel(
            name="OffStreetPSA",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("car_park_id", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=50)),
                ("total_spaces", models.IntegerField(blank=True, null=True)),
                ("available_spaces", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("car_park_id", "city")},
            },
        ),
    ]
