# Generated by Django 5.2.4 on 2025-07-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_space", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offstreetcp",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="offstreetcp",
            name="faredescription",
            field=models.TextField(blank=True, null=True),
        ),
    ]
