# Generated by Django 5.2.4 on 2025-07-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_space", "0002_offstreetcp_address_offstreetcp_faredescription"),
    ]

    operations = [
        migrations.CreateModel(
            name="DBUpdateTime",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("db", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("updatetime", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("db", "city")},
            },
        ),
    ]
